### PR TITLE
feat: add gnome 43 support

### PR DESCRIPTION
**Pull request by CleoMenezesJr**
Tested features
- [x] Isolate Workspaces
- [x] Isolate Monitors
- [x] Ignore Taskbar Windows
- [x] Detect Minimized Windows
- [x] Always Hide Overview on New Window
- [x] Window Checking Delay (ms)

https://user-images.githubusercontent.com/54215258/189492827-824bb18e-1ce8-406d-bd6c-a2329540d034.mp4

### CODE REVIEW

**Comment by jan-senaa** [comment]
I really love how you've tested all the features. I don't use GNOME anymore, so that's actually a pretty good relief for me. Thank you so much <3

**Comment by jan-senaa** [comment]
I will tag the release and upload it the day GNOME 43 gets released 👍🏼

**Comment by CleoMenezesJr** [comment]
> I really love how you've tested all the features. I don't use GNOME anymore, so that's actually a pretty good relief for me. Thank you so much <3

Thank you very much for the words. To be honest, I used this extension little, but I would like to help some extensions that I think are cool for version 43.

**Comment by CleoMenezesJr** [comment]
> I will tag the release and upload it the day GNOME 43 gets released 👍🏼



> I will tag the release and upload it the day GNOME 43 gets released 👍🏼
Cool, it would be nice to release before as GNOME 43 is in a beta phase and people could start to test it.

**Pull request merged**
